apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-rust-deploy
  labels:
    app: api-rust
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-rust
  template:
    metadata:
      labels:
        app: api-rust
    spec:
      containers:
      - name: api-rust
        image: unillusive-nonvitrified-leontine.ngrok-free.dev/api_rust:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        env:
        - name: GRPC_SERVER_URL
          value: "http://server-go-service:50051"
---
apiVersion: v1
kind: Service
metadata:
  name: api-rust-service
  labels:
    app: api-rust
spec:
  selector:
    app: api-rust
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
